
#
# Makefile for gridlabd models using CircleCI
#

#
# This is required for make rules that gridlabd needs
#
include Makefile.cnf

#
# Set the gridlabd command line flags here
#
# GLFLAGS0 are the flags used before the GLM file
# GLFLAGS1 are the flags used after the GLM file
#
GLFLAGS0=--verbose
GLFLAGS1=

#
# List the output files generated by the model
#
all: my_test.csv 

#
# List all internal model dependencies
#
my_test.glm: config.glm
